//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSQLEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public string AboutID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string Hotline { get; set; }
    }
}
