//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiddingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InRole
    {
        public string IdAccount { get; set; }
        public string TypeID { get; set; }
    
        public virtual TypeRole TypeRole { get; set; }
    }
}
