//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiddingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingGuide
    {
        public string DescriptionBid { get; set; }
        public string Hotline { get; set; }
    }
}
